### ISSUE TITLE
npm start 缺少包

### ISSUE THREAD

**Issue by chenkang084** [Brooooooklyn/learning-rxjs#13]
我checkout了master分支，npm install ,然后checkout seed分支，又执行了npm install ，npm start 还是提示有些module没有，试图安装了几个，还是有问题。麻烦你看一下是不是把所有的依赖都写进去了。或者，update一下readme

**Comment by Brooooooklyn** [comment]
我在 windows ，ubuntu 和 Mac 下均尝试从零安装，并没有遇到缺少包的报错，你可以把报错截图贴一下吗

**Comment by chenkang084** [comment]
好像在我的window上面不行。我在ubuntu上面试了，好了。算了，我close一下吧。谢谢！
