### ISSUE TITLE
build error: Cannot find type definition file for 'chai'

### ISSUE THREAD

**Issue by Hucy** [Brooooooklyn/learning-rxjs#4]
- windows 7
- node 4.x
- branch artic1 》 learn1
运行 `npm start` build 的时候报错   `Cannot find type definition file for 'chai' `
添加依赖 就好了。
```  json
"@types/chai": "^3.4.34"
```
这个不知道 是不是我这边的问题。

**Comment by Brooooooklyn** [comment]
这个是因为 RxJS 升级导致的问题
https://github.com/ReactiveX/rxjs/issues/2112
暂时可以用 `npm i @types/chai --save-dev` 解决

**Comment by Hucy** [comment]
thx

**Comment by Brooooooklyn** [comment]
close via https://github.com/teambition/learning-rxjs/pull/8
